//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meydanca_Adm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public int StadiumId { get; set; }
        public int ConctactId { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public System.DateTime Created { get; set; }
        public int RoomId { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Stadium Stadium { get; set; }
        public virtual Room Room { get; set; }
    }
}
